spring:
  application:
    name: hasfun-framework-springboot
  redis:
    cluster:
      nodes:
        - node1:7000
        - node2:7001
        - node3:7001
  kafka:
    clientId: hasfun-framework-springboot
    bootstrapServers:
      - node1:9092
      - node2:9092
      - node3:9092
    producer:
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
    consumer:
        # 默认消费者组
        group-id: hasfun-framework-springboot
        # 最早未被消费的offset
        auto-offset-reset: earliest
        # 批量一次最大拉取数据量
        max-poll-records: 1000
        # 自动提交
        auto-commit-interval: 1000
        enable-auto-commit: true
    # es相关配置
  data:
    elasticsearch:
      # 配置集群名
      cluster-name: elasticsearch-my   # 访问 es服务端 `http://127.0.0.1:9200/` 填写 `cluster_name` 对应的值
      # 配置节点信息，逗号分隔，如果没有指定，则启动ClientNode 【 注：9200->图形界面端、9300->程序端 】
      cluster-nodes: node1:9300
      # 开启 Elasticsearch 仓库(默认值:true)
      repositories:
        enabled: true



topicName:
  topic1: test
  topic2: test2

server:
  port: 9091
