spring:
  application:
    name: hasfun-framework-springboot
  redis:
    host: 47.100.240.207
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: -1ms


server:
  port: 9090
