spring:
  application:
    name: hasfun-framework-springboot
  redis:
#    jedis:
#      pool:
#        max-wait:5000
#        max-Idle:50
#        min-Idle:5
    cluster:
      nodes:
        - node1:7000
        - node1:7001
        - node2:7000
        - node2:7001
        - node3:7000
        - node3:7001

server:
  port: 9090
